language: ruby
rvm:
  - 2.2.2
  - 2.3.0
services:
  - memcached
before_script: rake appraisal:install
install: bundle install
script: bundle exec rake spec
notifications:
  recipients:
    - amikhailov83@gmail.com
